### ISSUE TITLE
Annotation Web: httpuri/europeanaid/@id relationship

### ISSUE THREAD

**Issue by rgraf** [europeana/annotation#19]
Missmatch between annotation id in JSON vs JSONLD
in JSON
AnnotationId = target.resourceId + annoNr
/15502/GG_8285/1
in JSON-LD
AnnotationId = target.@id(=httpuri) + annoNr 
http://europeana.eu/portal/record//15502/GG_8285.html/1 
need to clarify which is the correct format for annotation IDs and how to build them?
see also #21

**Comment by gsergiu** [comment]
need to conclude the discussion on the externally generated identifiers (How to deal with externally generated identifiers) in the specificatin document:
https://docs.google.com/document/d/1KaVQEAlCsKTNM17KvDplRe_ft200P-oL3qqhuBByi8M/edit#

**Comment by gsergiu** [comment]
Concluding this conversation from the external document, the following extension to the AnnotationId will be implemented.
 
1. In Target we will get an @id/httpUri:http://europeana.eu/portal/record//15502/GG_8285.html 

2. From this one, we will extract the europeanaId part /15502/GG_8285 
(to use in AnnotationID object)

3. For annotations created in Europeana Portal, the annotation ID will be generated internally as
{
resourceId:"/15502/GG_8285",
provider: "webanno",
annotationNr: 1//sequence generator
}

and will be serialized to:
@id: "http://data.europeana.eu/annotations/15502/GG_8285/webanno/1"

4. in case of hitstorypin annotations,

We must add a field to the annotation object
sameAs: "http://historypin.com/annotation/1234"
from which we will take over the external annotationNr 123 and "historypin" as provider into the AnnotationId 

{
resourceId:"/15502/GG_8285",
provider: "historypin",
annotationNr: 1234
}

and will be serialized to:
@id: "http://data.europeana.eu/annotations/15502/GG_8285/historypin/1234"

**Comment by rgraf** [comment]
In the case of specific resources, the resourceId might not necessarily be represented within the httpUri of the SpecificTarget.httpUri, but in the Source.httpUri. Eg. the Target might represent the thumbnail of europeana object, while the link to the europeana object will be represented in the target.source.http.uri
http://www.w3.org/TR/annotation-model/#specifiers-and-specific-resources

**Comment by gsergiu** [comment]
open annotation httpuri is used for generating the Webannotation "@id" (jsonld) attribute.
The europeana resource id in form of http://data.europeana.eu/item/{record id} is (recommended to be) used in target ...
see also search by record id specifications:
https://europeanadev.assembla.com/spaces/europeana-npc/tickets/554
