### ISSUE TITLE
Annotation Web: correct representation of resourceId in target

### ISSUE THREAD

**Issue by rgraf** [europeana/annotation#21]
JSON-LD.target.source.@id 
vs
JSON.target.europeanaId

see also: #19

e.g.
JSON-LD
 "target": {
        "@type": "[oa:SpecificResource,euType:IMAGE]",
        "contentType": "image/jpeg",
        "httpUri": "http://europeanastatic.eu/api/image?uri=http%3A%2F%2Fbilddatenbank.khm.at%2Fimages%2F500%2FGG_8285.jpg&size=FULL_DOC&type=IMAGE",
        "selector": {
            "@type": "[oa:SvgRectangle,euType:SVG_RECTANGLE_SELECTOR]",
            "dimensionMap": "[left:5,right:3]"
        },
        "source": {
            "@id": "/15502/GG_8285",
            "contentType": "text/html",
            "format": "dctypes:Text"
        },
        "targetType": "[oa:SpecificResource,euType:IMAGE]"
    },

JSON:
"target": {
    "contentType": "text-html",
    "mediaType": "image",
    "language": "de",
    "value": "Vlad IV. Tzepesch, der Pfähler, Woywode der Walachei 1456-1462 (gestorben 1477)",
    "httpUri": "http://europeana.eu/portal/record/15502/GG_8285.html",
    "targetType": "[euType:WEB_PAGE]",
    "europeanaId": "/15502/GG_8285"
},

**Comment by rgardien** [comment]
This should be data.europeana.eu.

Example: http://europeana.eu/portal/record/15502/GG_8285.html
Becomes: http://data.europeana.eu/item/15502/GG_8285

**Comment by gsergiu** [comment]
Additionally, there is a dupplication between the europeanaId in Target object after the source (InternetResource) attribute was added to the Target object. This needs to be clarified if the europeanaId is now redundant (e.g. at least has the same value as the resourceId in AnnotationId), and which is the primary source of information  for extracting the resource ID if both target.source and target.@id  are present in the JSON-LD input...

**Comment by rgraf** [comment]
1. the europeanaId attribute in the Target became redundant as it is part of the request during creation and read of the objects
(get/post:) /annotationld/{collection}/{object}.json(ld) 

2. It is also part of the AnnotationId and Target.httpuri, which can be used for validation purposes.

Needs to be removed...

**Comment by gsergiu** [comment]
see also discussions in:
(search by record id)
https://europeanadev.assembla.com/spaces/europeana-npc/tickets/554#/activity/ticket:
(epic v1)
https://europeanadev.assembla.com/spaces/europeana-npc/tickets/549

**Comment by gsergiu** [comment]
see also #49
