### ISSUE TITLE
Annotation Web: context information missing when reading object in JSON-LD

### ISSUE THREAD

**Issue by rgraf** [europeana/annotation#22]
The context information is available after the creation of an object when using JSON-LD, 
    "@context": 
{
    "oa": "http://www.w3.org/ns/oa-context-20130208.json"
}

but is not available in the response when reading an object:
http://62.218.164.176/annotation-web/annotations//15502/GG_8285/2.jsonld

**Comment by gsergiu** [comment]
obsoleted ticket, see updated specifications #47
