### ISSUE TITLE
Annotation-web: management console

### ISSUE THREAD

**Issue by rgraf** [europeana/annotation#23]
add an admin.html file and an AdministrationRest interface in order to facilitate the invocation of aministration/moderation functionality like:
- delete annotation by id (delete in mongo, delete in solr/annotation, but not the TAGS, either in mongo nor in solr/tag!! )
- delete tag by id (delete in mongo, delete in solr/tag but only when no annotation uses the tag, send an error message otherwise)
- index annotation by id (forces reindexing of the annotation, which means deletion in solr/annotation if exists and creation of new entry in solr/annotation)
- disable annotation by id (add the field disabled to annotation object, set it to true in database and remove the annotation from the solr/annotation)

**Comment by gsergiu** [comment]
Use appropriate HTTP methods for each of the interface method. 
See tutorial: http://www.restapitutorial.com/lessons/httpmethods.html

However HTML doesn't support PUT and DELETE, therefore we have to use the Spring-MVC solution for method conversion:
http://spring.io/blog/2009/03/08/rest-in-spring-3-mvc/ 
(see section method conversion)
