### ISSUE TITLE
Annotation Web: Specification for List Annotations as JSON-LD 

### ISSUE THREAD

**Issue by rgraf** [europeana/annotation#29]
List annotations for Europeana Object/Resource method is currently implemented only for JSON format
get /annotations/{collection}/{object}.json 

The equivalent method in JSON-LD format is needed.
get /annotations/{collection}/{object}.jsonld 

In order to implement this method the specification of the response object needs to be created.

**Comment by gsergiu** [comment]
The current representation follows the conventions of the search api, but this is not compliant with JSON-LD because:
1. Annotations are serialized in JSON now, they need to be serialized using JSONLD serializers
2. New Json-ld context, which includes the extra fields of the annotation ... see the current implementation for example:

{
  "action": "/annotations/search.jsonld",
  "success": true,
  "itemsCount": 4,
  "totalResults": 4,
  "items": [
    {
      "annotationId": {
        "annotationNr": 1434380225051,
        "provider": "historypin"
      },
      "type": "oa:Annotation",
      "internalType": "OBJECT_TAG",
      "annotatedAt": 1425034843000,
      "annotatedBy": {
        "internalType": "PERSON",
        "name": "John Smith",
        "openId": "https://www.historypin.org/en/person/55376/",
        "inputString": "{\"@id\":\"https:\\/\\/www.historypin.org\\/en\\/person\\/55376\\/\",\"@type\":\"foaf:Person\",\"name\":\"John Smith\"}",
        "type": "foaf:Person"
      },
      "body": {
        "values": [],
        "resourceIds": [],
        "inputString": "{\"@type\":\"oa:SemanticTag\",\"related\":\"http:\\/\\/dbpedia.org\\/resource\\/Paris\"}",
        "internalType": "TAG",
        "multilingual": {},
        "tagId": "557ee7c54324136c9bdea2c0",
        "type": [
          "TAG",
          "oa:SemanticTag"
        ]
      },
      "target": {
        "httpUri": "http://data.europeana.eu/item/123/xyz",
        "value": "http://data.europeana.eu/item/123/xyz",
        "values": [],
        "resourceId": "/123/xyz",
        "resourceIds": [],
        "inputString": "http://data.europeana.eu/item/123/xyz",
        "internalType": "WEB_PAGE",
        "type": "WEB_PAGE"
      },
      "motivatedBy": "oa:tagging",
      "serializedAt": 1425124834000,
      "serializedBy": {
        "internalType": "SOFTWARE",
        "name": "http://www.historypin.org",
        "homepage": "http://www.historypin.org",
        "inputString": "http://www.historypin.org",
        "type": "SOFTWARE"
      },
      "motivationType": "TAGGING",
      "disabled": false
    },
    {
      "annotationId": {
        "annotationNr": 1434380231982,
        "provider": "historypin"
      },
      "type": "oa:Annotation",
      "internalType": "OBJECT_TAG",
      "annotatedAt": 1425034843000,
      "annotatedBy": {
        "internalType": "PERSON",
        "name": "John Smith",
        "openId": "https://www.historypin.org/en/person/55376/",
        "inputString": "{\"@id\":\"https:\\/\\/www.historypin.org\\/en\\/person\\/55376\\/\",\"@type\":\"foaf:Person\",\"name\":\"John Smith\"}",
        "type": "foaf:Person"
      },
      "body": {
        "value": "church",
        "values": [],
        "resourceIds": [],
        "inputString": "church",
        "internalType": "TAG",
        "multilingual": {},
        "tagId": "557ee7c84324136c9bdea2c2",
        "type": [
          "TAG"
        ]
      },
      "target": {
        "httpUri": "http://data.europeana.eu/item/123/xyz",
        "value": "http://data.europeana.eu/item/123/xyz",
        "values": [],
        "resourceId": "/123/xyz",
        "resourceIds": [],
        "inputString": "http://data.europeana.eu/item/123/xyz",
        "internalType": "WEB_PAGE",
        "type": "WEB_PAGE"
      },
      "motivatedBy": "oa:tagging",
      "serializedAt": 1425124834000,
      "serializedBy": {
        "internalType": "SOFTWARE",
        "name": "http://www.historypin.org",
        "homepage": "http://www.historypin.org",
        "inputString": "http://www.historypin.org",
        "type": "SOFTWARE"
      },
      "motivationType": "TAGGING",
      "disabled": false
    },
    {
      "annotationId": {
        "annotationNr": 1434381935937,
        "provider": "historypin"
      },
      "type": "oa:Annotation",
      "internalType": "OBJECT_TAG",
      "annotatedAt": 1425034843000,
      "annotatedBy": {
        "internalType": "PERSON",
        "name": "John Smith",
        "openId": "https://www.historypin.org/en/person/55376/",
        "inputString": "{\"@id\":\"https:\\/\\/www.historypin.org\\/en\\/person\\/55376\\/\",\"@type\":\"foaf:Person\",\"name\":\"John Smith\"}",
        "type": "foaf:Person"
      },
      "body": {
        "value": "church",
        "values": [],
        "resourceIds": [],
        "inputString": "church",
        "internalType": "TAG",
        "multilingual": {},
        "tagId": "557ee7c84324136c9bdea2c2",
        "type": [
          "TAG"
        ]
      },
      "target": {
        "httpUri": "http://data.europeana.eu/item/123/xyz",
        "value": "http://data.europeana.eu/item/123/xyz",
        "values": [],
        "resourceId": "/123/xyz",
        "resourceIds": [],
        "inputString": "http://data.europeana.eu/item/123/xyz",
        "internalType": "WEB_PAGE",
        "type": "WEB_PAGE"
      },
      "motivatedBy": "oa:tagging",
      "serializedAt": 1425124834000,
      "serializedBy": {
        "internalType": "SOFTWARE",
        "name": "http://www.historypin.org",
        "homepage": "http://www.historypin.org",
        "inputString": "http://www.historypin.org",
        "type": "SOFTWARE"
      },
      "motivationType": "TAGGING",
      "disabled": false
    },
    {
      "annotationId": {
        "annotationNr": 1434381937058,
        "provider": "historypin"
      },
      "type": "oa:Annotation",
      "internalType": "OBJECT_TAG",
      "annotatedAt": 1425034843000,
      "annotatedBy": {
        "internalType": "PERSON",
        "name": "John Smith",
        "openId": "https://www.historypin.org/en/person/55376/",
        "inputString": "{\"@id\":\"https:\\/\\/www.historypin.org\\/en\\/person\\/55376\\/\",\"@type\":\"foaf:Person\",\"name\":\"John Smith\"}",
        "type": "foaf:Person"
      },
      "body": {
        "values": [],
        "resourceIds": [],
        "inputString": "{\"@type\":\"oa:SemanticTag\",\"related\":\"http:\\/\\/dbpedia.org\\/resource\\/Paris\"}",
        "internalType": "TAG",
        "multilingual": {},
        "tagId": "557ee7c54324136c9bdea2c0",
        "type": [
          "TAG",
          "oa:SemanticTag"
        ]
      },
      "target": {
        "httpUri": "http://data.europeana.eu/item/123/xyz",
        "value": "http://data.europeana.eu/item/123/xyz",
        "values": [],
        "resourceId": "/123/xyz",
        "resourceIds": [],
        "inputString": "http://data.europeana.eu/item/123/xyz",
        "internalType": "WEB_PAGE",
        "type": "WEB_PAGE"
      },
      "motivatedBy": "oa:tagging",
      "serializedAt": 1425124834000,
      "serializedBy": {
        "internalType": "SOFTWARE",
        "name": "http://www.historypin.org",
        "homepage": "http://www.historypin.org",
        "inputString": "http://www.historypin.org",
        "type": "SOFTWARE"
      },
      "motivationType": "TAGGING",
      "disabled": false
    }
  ]
}

**Comment by gsergiu** [comment]
will be defined within the:
https://europeanadev.assembla.com/spaces/europeana-npc/tickets/554#/activity/ticket:

**Comment by gsergiu** [comment]
see also annotation search:
#63
