### ISSUE TITLE
Correct syntax of multilingual tags/body

### ISSUE THREAD

**Issue by rgardien** [europeana/annotation#36]
When posting a new annotation via the POST /annotation.jsonld function and the need for a multilingual representation of the body, this does not seem to work, or I am doing something wrong.

The body that works is:

``` json
    "body": [
        "Tags: helicopter; gulls; black headed gulls; haringey; river lea",
        "last test",
        "new tag"
    ],
```

This returns:

``` json
 "body": [
    "Tags: helicopter; gulls; black headed gulls; haringey; river lea",
    "last test",
    "new tag"
  ],
```

However, this lacks information on the language. So I want to do it like this:

``` json
  "body": [
        {
            "language": "en",
            "@type": [
                "oa:Tag",
                "oa:EmbeddedContent"
            ],
            "value": "Tags: helicopter; gulls; black headed gulls; haringey; river lea"
        },
        {
            "language": "en",
            "@type": [
                "oa:Tag",
                "oa:EmbeddedContent"
            ],
            "value": "last test"
        },
    ],
```

This returns:

``` json
  "body": {
    "@type": "[TAG]",
    "multilingual": ""
  },
```

Even without the @type it does not give the same output as I put in.
Question: is this syntax incorrect, or is this a bug?

Thanks!

**Comment by rgraf** [comment]
The syntax for Annotations API is implemented for the SimpleTagging and ObjectLinking scenarios according to the document:
https://docs.google.com/document/d/15DaWKOHHxqxv4QxNi4wHxCbVzfnJu8nUX8GUK_mQ5ek

**Comment by rgardien** [comment]
OK, thanks for your quick response! 

I presumed, given the "multilingual" response in the API call that the multilingual use-case would be supported. Is that the case or not?

If not, then fine for now, we'll add that in a later iteration and include it in the specification.

**Comment by rgraf** [comment]
I believe for that use case we will need related specification and a sample.

**Comment by gsergiu** [comment]
I think that the parsing of multilingual fields is not implemented for Json Ld.
Also, we have some basic support in the JSON based API, still I’m not sure if this is the solution that we want to use in the end.
So .. we should think what we need  exactly and to write the specification, probably by combining the Contextual Entities,  JSKOS and Web Annotation specifications.

BR,

Sergiu

**Comment by gsergiu** [comment]
The tag support was removed in the last version, the multilingual values are supported for FulltextResources
