### ISSUE TITLE
Automated Integration Tests   

### ISSUE THREAD

**Issue by rgraf** [europeana/annotation#39]
The automated integration tests will be implemented in the Annotation-Client component.
This way, we will test both the Annotation API, by sending http requests and the utility classes used for parsing annotations. 

The following test cases need to be implemented for the current version of the Europeana Annotation API:

1.  Create annotation for historyPin
    * simple tag
    * multiple tags
    * semantic tag
    * object linking

2.  Create annotations for webanno
    * simple tag with provider webanno
    * simple tag without provider

3.  Get by provider and Annotation NR 
(create a new annotation and read the annotation with same id (provider+annotationNr). compare the fields of the two annotations)
    * semantic tag 
    * object linking

4. Search by target.httpUri and by resourceId
(create a new annotation and search the annotations by target/resourceId. 
Verify that the ID of the annotation is present in the search results.
)
    * semantic tag 
    * object linking

5. Search objects with multiple targets      
(create a new annotation and search the annotations by target/resourceId of each target.httUri 
Verify that the ID of the annotation is present in the search results.
)
    * object linking

6. Exception tests 
    (check success=false, check error message)
   * create annotation with provider historyPin without annotation Nr
   * create annotation with provider webanno with annotation Nr

**Comment by gsergiu** [comment]
The input data needs to be read from json files

**Comment by gsergiu** [comment]
the basic tests for the current version of the specification were implemented.
