### ISSUE TITLE
Annotation Web: disable annotation

### ISSUE THREAD

**Issue by rgraf** [europeana/annotation#46]
It should be possible to disable annotation 'disabled'=true. Disabled annotations should not be visible to a user e.g. by searching annotaitons.

**Comment by gsergiu** [comment]
first version is implemented as "DELETE" method now, according to the web annotatation specifications
see: https://docs.google.com/document/d/1R2_RDuP5E2n0SBnZOqvjedqmKVoBavo6wtS0pN1UJtA/edit#
