### ISSUE TITLE
Avoid multiple JUnit dependencies (of different versions) in your classpath

### ISSUE THREAD

**Issue by rgraf** [europeana/annotation#68]
Make sure that there are no multiple JUnit dependencies (of different versions) in your classpath. Otherwise JUnit tests employing SpringJUnit4ClassRunner.class will not work.

**Comment by gsergiu** [comment]
Eclipse JUNIT test runner has an embedded junit which is actually not visible in the classpath.
If the projects explicitly declare the junit V4.1x dependency, this will take precedence over the transitive dependencies and eclipse plugin dependencies.

**Comment by rgraf** [comment]
also ... the junit test runner might use an older junit which will result in the fact that you cannot run individual methods from junit panel. (a nosuchmethod excception is thrown). In this case you need to update the run configuration by adding manually the (eclipse) junit library on the first possition of the classpath. see also http://stackoverflow.com/questions/4019016/junit-java-lang-nosuchmethoderror-junit-framework-comparisonfailure-getexpected
