### ISSUE TITLE
Add sorting to Annotation search API

### ISSUE THREAD

**Issue by rgraf** [europeana/annotation#70]
Enable sorting fields and sorting order for Annotation search API.

**Comment by gsergiu** [comment]
The reindexSet api method should work under the best effort principle, which means that it should reindex all items for which this operation is possbile. It must write into the logs the errors which prevent indexing some objects (e.g. old mongo annotations that don't have valid annotation ids anymore) At the end a report must be return to the user indicating the number of successsfully indexed items and the number of items for which the reindexing failed.
